on:
  push:
    branches:
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

name: Publish Platform

permissions:
  contents: write

jobs:
  build:
    name: datalens-us
    runs-on: ubuntu-24.04
    if: |
      startsWith(github.ref, 'refs/heads/release-') &&
      github.event.head_commit.author.username == 'robot-charts'
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
          fetch-depth: 0
      - name: Get version
        run: |
          set -e

          RELEASE_TAG=$(git describe --tags --abbrev=0)
          echo "RELEASE_TAG=$RELEASE_TAG" >> "$GITHUB_ENV"
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          commitish: ${{ github.ref }}
          body: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false
      - name: Save workflow ref
        run: |
          mkdir -p ./workflow_ref
          echo "${{ github.ref }}" > ./workflow_ref/ref
          echo "${{ env.RELEASE_TAG }}" > ./workflow_ref/release_tag
      - uses: actions/upload-artifact@v4
        with:
          name: workflow_ref
          path: ./workflow_ref/
          retention-days: 30
          overwrite: true
